Add support for jsoniter Json
softwaremill/sttp pull request #1248
Opened 2022-01-09 11:20 UTC by borissmidt

Before submitting pull request:
- [x ] Check if the project compiles by running `sbt compile`
- [ ] Verify docs compilation by running `sbt compileDocs`
- [ ] Check if tests pass by running `sbt test`
- [ ] Format code by running `sbt scalafmt`

2022-01-09 13:45 UTC, borissmidt commented
Offtopic; I also updated the openApi generator to use sttp3. 
https://github.com/OpenAPITools/openapi-generator/pull/11260

2022-01-12 18:35 UTC, Pask423 requested changes

2022-01-12 18:35 UTC, Pask423 commented on json/jsoniter/src/main/scala/sttp/client3/jsoniter/SttpJsoniterJsonApi.scala
> +    try {
maybe here you could use `Try` and`.toEither`  with`left.map` instead of try {} catch

2022-01-12 18:35 UTC, Pask423 commented on build.sbt
> +lazy val jsoniter = (projectMatrix in file("json/jsoniter"))
You should add jsoniter to `allAggregates` variable and probably also to `docs` as dependency

2022-01-12 18:41 UTC, Pask423 commented
Could you merged newest master it should solve problem with js tests.
It would be also great if you could write docs for  `jsoniter` similar to one written for `zio-json`.
Please check if all files are correctly formatted with `fmt`.

2022-01-12 19:17 UTC, borissmidt commented
I see one big problem with jsoniter and sttp and that is that sttp uses either and option a lot.
The it is possible in jsonIter to handle the option with the implicit def.
But the Either isn't really that safe so the user has to manually define an implicit val for every variant of either he wants to use.

So i think jsoniter needs to be improved for our usecase.

2022-01-12 20:36 UTC, Pask423 commented
That can be quite problematic from user perspective. I am not that familiar with jsoniter to propose any workaround for this.
BTW I still see some merge conflicts could you resolve them ?

2022-01-12 21:14 UTC, borissmidt commented
I could only make a workaround for 'option[t]'.
So i think changes have to be made to jsoniter before we can support it in this library.

For Either i couldn't really make a good workaround.

So we might better close the pr and maybe we can best keep the github issue open and comment these issues on there for future reference?

2022-01-14 10:49 UTC, adamw commented
Hm I don't think we need any special `Option`/`Either` support. The options/eithers that appear in signatures are used to represent cases where either JSON parsing failed, or we received a non-200 response. So we don't typically need json codecs for these types, only for whatever is the "root" type.

2022-01-18 11:01 UTC, borissmidt commented
I've removed the ambiguous Either tests and now i expect the use of `asJsonEither` so it is clear that you either have an error of type Left or a body of type Right.

2022-01-18 21:31 UTC, Pask423 commented on json/jsoniter/src/main/scala/sttp/client3/jsoniter/SttpJsoniterJsonApi.scala
> +      case NonFatal(e) => new RuntimeException(e)
I think we should go back to previous version of Exception handling

2022-01-19 12:15 UTC, Pask423 commented
Great just resolve conflicts and I think we can merge it

2022-01-20 19:58 UTC, Pask423 commented
There is an error with downloading dependency
![image](https://user-images.githubusercontent.com/59844835/150412797-1df27efc-685a-488b-8e2d-88561c0dbd83.png)

2022-01-20 20:12 UTC, borissmidt commented
scala 3 macro support still needs to be added. I'll remove scala3 from the possible builds.

2022-01-24 14:59 UTC, Pask423 approved these changes

2022-01-24 16:32 UTC, merged